BEGIN;
​
DROP TABLE IF EXISTS Songs;
​
CREATE TABLE Songs (
    SongID INT(5) NOT NULL AUTO_INCREMENT,
    Song_name VARCHAR(50) NOT NULL,
    Artist VARCHAR(50) NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    PRIMARY KEY(SongID)
);

DROP TABLE IF EXISTS Chords;
​
CREATE TABLE Chords (
    ChordID INT(5) NOT NULL AUTO_INCREMENT,
    Chord_Name VARCHAR(50) NOT NULL,
    Chord_Symbol VARCHAR(10) NOT NULL,
    PRIMARY KEY(ChordID)
);

DROP TABLE IF EXISTS Chords_Songs;
​
CREATE TABLE Chords_Songs (
    ID INT(5) NOT NULL AUTO_INCREMENT,
    SongID INT(5) NOT NULL,
    ChordID INT(5) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(SongID) REFERENCES Songs(SongID),
    FOREIGN KEY(ChordID) REFERENCES Chords(ChordID)
);
​
COMMIT;
